# Jekyll Configuration for ParentShopper
title: ParentShopper
description: Real parent reviews for real parents. No sponsored content, just honest recommendations.
baseurl: "/parentshopper"
url: "https://jaimev365.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

# Exclude files from processing
exclude:
  - README.md
  - netlify.toml
  - temp-REMOVE LATER-DO NOT PUSH/
  - test-ssi-netlify.html

# Include files
include:
  - _includes

# Collections
collections:
  reviews:
    output: true
    permalink: /:collection/:name/
  categories:
    output: true
    permalink: /:collection/:name/
  guides:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "reviews"
    values:
      layout: "review"
  - scope:
      path: ""
      type: "categories"
    values:
      layout: "category"
  - scope:
      path: ""
      type: "guides"
    values:
      layout: "guide"
